apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amurpo/argocd-example-apps
    targetRevision: HEAD
    path: lab-gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true