apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-password
  namespace: default
spec:
  encryptedData:
    password: AgBQ4LJgz3YpyPp2bFM/d76JR4lFpaXVt7qIZDOK4fhljkA2WMaSIZ7kKAVk6S5Fx5qSvOejGI+OZCO9uaQPbx5JID8pwPaURP7HinVTJkTH/pb+qA5Xv6n7/YBzW0iUMbZfFtnS7a2jffiinqSEAmpl1pLfcQBHBpdTkawlvS2dPj9NnHLQzo80Jct+Lhhp/mPKheB1P5oJW+JC8CsJucEooInZDW1tx2eL893z4Kw+LDE7KYKI4r+Pc3LDe93y0QKV2TXmDxyAeUVapINwbknvOHOxd8VLq22cl34otVq6ylx/dIxswVcI90McS86fnOVBThkLEq2bgM+MvX4E1Em11GKqEUyEz6jSOLffb4cikQ6PfdtVjMlbeE4j0MozWTqfge1s1wxGv/2Dpx4whtLKSiPIjIhKZyib6D/dIXo+jGb9C/tnK1nQ9QRCQoDSbhuwzh7r14zMM/ytl4ZNey/dQR43c9yV+jM1CbpfwaI42bK9fxa+qSiNgRWSN1tq4QUcuxeDTdxwPhtAmzJOQcI/3azGiniR9a0CvHzEmHDGZgKCNTQD78xpeNX+RISvowY5Dwl3JBiQDoTN2sekJxu8ty846cFHVMT9KoeZutvmLWqFvOWpmfhPyHfnlUCekIVfwiDRYQCxYOoC+SDQnl2YtsgeQDInBUlkCRrpj5z8pnpRfJ2ndUIZTnaeHT0U9k3mV/1EY8WqshipAh0YwP3FbF4Qniro/5M=
    username: AgBboxEMQtbmhRfV0Y55Q9MMDZREu3G1W/jpvT3ok8vuNsPOnZDR3b/i8CLsW2QFohNzecVLvYx9tmesU9pK6fYpQF5mccLBUaIIqqth+xZMN37iEFcZo0wKocHJQ0yYqfZxWIEQiREpBtxiqswlYglKwKRLf5fPN6Vd9xKD8Jp3Jrtltyw7B/aQMk72ugonFMweQRYyDOhdOjUrwt09kgvBevom4e4ZQ0Sd+MKNucHk0+jjggJ5n0Yx4/2Kr7nzLS8lUn6TlbzwOkGAnmhKnJE1BEbMCANDw+zLsyY3o5wnXwkZJJKSnTa+flgtpT7ueUOgBiqrirpnmwO8n7sxBLqM19HWN+fhyXiQhkEa6jOkCIPPoIpCzAjSEZEZzY6eLc3IS2LOuAPAUKgBClMX1DiXsLPCshWa9eYyWF2O5JdL+/AZNjKyHl7ZbBu00V5ib1lO4GkpL9F4EcDg6rVO9OBzgxaGHwjkLetHTpQKDGIhUXd9CO0rPzh89bI/bqWG2ZaIB7bDxhZMH7MKbUSwUcqkeuSbfLUXEzngcWDQbmHUBRxMtYTPE88k8UsPnTOXb2ivaYJBn5ci+y113dmnaAOliO+8oHYILJv02IQZl6/IcN1J5firIZQytd/8ONbqVdU/bj64CtdDy3JUH7xn7feYZYsEq9cvbenc3aHqRdfajqoDmnOTF1YpRdbmQqexlCKOwIMLVw==
  template:
    metadata:
      creationTimestamp: null
      name: database-password
      namespace: default
    type: Opaque
---
