apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-consumer
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secret-consumer
  template:
    metadata:
      labels:
        app: secret-consumer
    spec:
      containers:
      - name: app
        image: nginx:1.21
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: secret-consumer-service
  namespace: default
spec:
  selector:
    app: secret-consumer
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
