apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sealed-database-secret.yaml
- deployment.yaml

commonLabels:
  app.kubernetes.io/name: secret-consumer
  app.kubernetes.io/instance: demo
