apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: temp-secret
  namespace: default
spec:
  encryptedData:
    password: AgAfnlb8NGlAJPMJ+2OWWIwTWMEjeOoztwL0sAtw3qWcRzlBZqQQ6moWMbJcmjEs23NtCWEnAxasNPz2PSWdN34aQP5ZdS5BS1rshLfujI/unjrKUTuqPw5BxAm3xcSAj307Xl/PDzU36XPM+FnwJF9eaJyaHAq+gG+4foXS8I3voV91H0+efDZFzvMu9FhLUyKTF1IHiqtddio97CSZh4CZP9UOOB2VGB119qhxApa32eC3+M1KhvlwyF6GW/g0dbC0TpSleXLXynNe7OTTll8xnWURflK6WkSj4UHohnrmJpqY5+35YYQSx7F7D01I4+GqYB3+1J9ZdFFGEbCe+eMu7Wi+JqpI3ekT7O5H1yvmssLchRAarBo2/74NvuwM2dHQ476XVwyXa1W1Udh679PqwL7EHv/L4QT9Q7CVArXVzMVRz5ZmyUjNE0Op17BvGzrgcmItSAmlFut0yVAVxzBsOjbXBbqAcXRD1kwETr2y0FTkfyyPCd2PRAGLay0AyBYg+XIrM7T0EJOQdGrVYJZPNL1ogDt+wJSUbvDXv+NVxdGpXS3bS2L4Sk+znR1ZalJUAxY3xfRkfHz4Pt9Oodv0ZyKqkOS5VFjGvcBrroJovX6AL2kcY7WncYQPgoWXLORgSWIzZqV5D2ceM9lhKp4RXqPSMGEolmm2OHT1eWzF+J57htiYOcdtYqj8YY/om9i6+fI5w0GjLXBubMHbmg==
    username: AgAjLK4FAcqXNX+Rvx6SsPPi5MRPywnU15QB7yC6fd1sU9KA7l2KqMVugz5lmKKc/F/GBU5JYdoMB3reQrScxEn67LbswJNCbQ3JARJ1DBad7dT2mi4I2XGPt2C/uwemcwizWV9/Q8kLxznRyvzEcKeWHaX492qRC99JZBeXuUwM7SCFrsYjEYOdOUDsY9vZ4KyvhJqSoRmHxve9+tjyTsrBWNPeiujzaiXGWoP0PiyajcaWNUGg/Kc4avl9N1H1QUyafb2z/sF8yXJox1kxs3vYZa4kKPqnwzhI70+yyfZTRkj6l2kvzAPBa8amqiHoW4mXTVJSuk55zUr19GlOsQMezEBPD/609Mq49Wqj9pd3CLuUABnBfwBOSTfkP6xx9qAy24zgKY245Kk/+0zI1TAyZ3A7aefcQV06phdQpbxhf1g2cUXH+JMDUpeAq3MFvhl3JFvt+guLqFJX9w+gQ6CUerryps2cy1XvHWaPAR/wBKJdhmss1ffKGXNSQtntapmSotPguLrccD/FOShc3RmZtYj58q1PhNcb8lekD8zr96BMKmlOi0VIlHVqsUQmpGBMiURuZlVi2bm6PjlifhghlR7Pux5/fscaPjh1gnTHdpJL58REJZHN170gNqkvzqyZw1IT0VQwTwvq3ggPoXHq9saGU2teSsU1lIWalO/djnrA6HP7AmcxKA7mCi1UvlAyq0+LlA==
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: default
---